version: '3'

services:
  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - "/Users/max/Documents/Work/BigMarine/wo-backup-04-03-2019/wo:/wo-dump" # dump folder
      - "/Users/max/Documents/Work/BigMarine/mongo/bigmarine:/data/db"         # database persistence
    environment:
      TZ: "Europe/London"
    networks:
      - "bigmarinenetwork"
  wo:
    image: "big-marine-meteor:dev"
    volumes:
      - "/Users/max/Documents/Work/BigMarine/big-marine-git/web-observatory/src:/home/docker/wo-src"
      - "./docker/startup.sh:/startup.sh"
    ports:
      - "3000:3000" # has to match environment.PORT below
    links:
      - "mongo:mongo"
    depends_on:
      - "mongo"
    environment:
      TZ: "Europe/London"
      MONGO_URL: "mongodb://mongo:27017/wo"
#      PORT: "4000" # doesn't seem to be working
#      HTTP_FORWARDED_COUNT: "1" # however many number of proxies you have running before your Meteor application
      BIND_IP: "127.0.0.1"
    networks:
      - "bigmarinenetwork"

networks:
  bigmarinenetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16